// Convenience header for users of the api_proto component.
// Pulls in the nanopb-generated bindings and exposes the wire-format
// message-type IDs used in the plaintext framing (these are NOT proto
// field numbers — they are the second varint in each frame).
//
// Keep MessageId in sync with the `option (id) = N;` lines in upstream
// esphome/components/api/api.proto.

#pragma once

#include "api_subset.pb.h"

#include <cstdint>

namespace proxyapi {

enum MessageId : uint16_t {
  MSG_HELLO_REQUEST = 1,
  MSG_HELLO_RESPONSE = 2,
  MSG_CONNECT_REQUEST = 3,
  MSG_CONNECT_RESPONSE = 4,
  MSG_DISCONNECT_REQUEST = 5,
  MSG_DISCONNECT_RESPONSE = 6,
  MSG_PING_REQUEST = 7,
  MSG_PING_RESPONSE = 8,
  MSG_DEVICE_INFO_REQUEST = 9,
  MSG_DEVICE_INFO_RESPONSE = 10,
  MSG_LIST_ENTITIES_REQUEST = 11,
  MSG_LIST_ENTITIES_DONE_RESPONSE = 19,
  MSG_SUBSCRIBE_LOGS_REQUEST = 28,

  MSG_SUBSCRIBE_BLE_ADVERTISEMENTS_REQUEST = 66,
  MSG_BLUETOOTH_DEVICE_REQUEST = 68,
  MSG_BLUETOOTH_DEVICE_CONNECTION_RESPONSE = 69,
  MSG_BLUETOOTH_GATT_GET_SERVICES_REQUEST = 70,
  MSG_BLUETOOTH_GATT_GET_SERVICES_RESPONSE = 71,
  MSG_BLUETOOTH_GATT_GET_SERVICES_DONE_RESPONSE = 72,
  MSG_BLUETOOTH_GATT_READ_REQUEST = 73,
  MSG_BLUETOOTH_GATT_READ_RESPONSE = 74,
  MSG_BLUETOOTH_GATT_WRITE_REQUEST = 75,
  MSG_BLUETOOTH_GATT_READ_DESCRIPTOR_REQUEST = 76,
  MSG_BLUETOOTH_GATT_WRITE_DESCRIPTOR_REQUEST = 77,
  MSG_BLUETOOTH_GATT_NOTIFY_REQUEST = 78,
  MSG_BLUETOOTH_GATT_NOTIFY_DATA_RESPONSE = 79,
  MSG_SUBSCRIBE_BLUETOOTH_CONNECTIONS_FREE_REQUEST = 80,
  MSG_BLUETOOTH_CONNECTIONS_FREE_RESPONSE = 81,
  MSG_BLUETOOTH_GATT_ERROR_RESPONSE = 82,
  MSG_BLUETOOTH_GATT_WRITE_RESPONSE = 83,
  MSG_BLUETOOTH_GATT_NOTIFY_RESPONSE = 84,
  MSG_UNSUBSCRIBE_BLE_ADVERTISEMENTS_REQUEST = 87,
  MSG_BLUETOOTH_LE_RAW_ADVERTISEMENTS_RESPONSE = 93,
};

}  // namespace proxyapi
